'use strict';

export default {
  ADD_NODE: 'ADD_NODE',
  UPDATE_NODE: 'UPDATE_NODE',
  DELETE_NODE: 'DELETE_NODE',
  SELECT_NODE: 'SELECT_NODE',
  UPDATE_EDGE: 'UPDATE_EDGE',
  ZOOM_AND_POSITION: 'ZOOM_AND_POSITION',
  CREATE_EDGE: 'CREATE_EDGE',
  DRAW_LINE_START: 'DRAW_LINE_START',
  DRAW_LINE: 'DRAW_LINE',
  REMOVE_DRAWN_LINE: 'REMOVE_DRAWN_LINE'
};
